# inventory.yml
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_diploma
    ansible_python_interpreter: /usr/bin/python3
  
  children:
    bastion:
      hosts:
        bastion:
          ansible_host: 93.77.191.153
    
    web:
      hosts:
        web1:
          ansible_host: 10.0.10.10
        web2:
          ansible_host: 10.0.20.10
    
    prometheus:
      hosts:
        prometheus:
          ansible_host: 10.0.10.20
    
    grafana:
      hosts:
        grafana:
          ansible_host: 10.0.1.20
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_diploma
          ansible_user: ubuntu
          grafana_public_ip: 93.77.182.145 # добавляем публичный IP
          grafana_port: 3000
    
    elasticsearch:
      hosts:
        elasticsearch:
          ansible_host: 10.0.10.30
    
    kibana:
      hosts:
        kibana:
          ansible_host: 10.0.1.30
